[toolchain]
solana_version = "2.1.5"

[features]
resolution = true
skip-lint = false

[programs.mainnet-beta]
cpi_swap_program = "58vxQT1Ky9NcYCi8c9NggViKaA7GyYRkkhaxuZKFHxn8"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "mainnet-beta"
wallet = "~/.config/solana/devnet.json"

[scripts]
test-mainnet = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/newTest.ts"
deploy-mainnet = "solana program deploy target/deploy/cpi_swap_program.so --program-id target/deploy/cpi_swap_program-keypair.json -u mainnet-beta --use-rpc --with-compute-unit-price 100"